# 예외 처리

## 1. 개요

- 예외 처리는 발생한 에러를 해결하는 방법이다.

## 2. try-except

- try: 오류가 발생할 가능성이 있는 코드를 실행한다. 예외가 발생하지 않으면 except 없이 종료한다.
- except: 예외가 발생하면 except 절을 실행한다.

```python
try:
		num = input('숫자입력 :') print(int(num))
except:
		print('숫자가 아닙니다')

try:
		num = input('숫자입력 :') print(int(num))
except ValueError: 
  	print('숫자가 아닙니다')
```
- 복수의 예외 처리도 가능하다.

```python
try:
		num = input('100으로 나눌 값을 입력하시오: ') 
    100/int(num)
except (ValueError, ZeroDivisionError): 
  	print('제대로 입력해줘')

try:
		num = input('값을 입력하시오: ') 
    100/int(num)
except ValueError: 
  	print('숫자를 넣어주세요.')
except ZeroDivisionError: 
  	print('0으로 나눌 수 없습니다.')
except:
		print('에러는 모르지만 에러가 발생하였습니다.')
```
## 3. 예외 발생시키기

- raise를 통해 예외를 강제로 발생시킬 수 있다.

```python
raise <표현식>(메시지)
```